name: Nox Tests

on:
  push

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Nox
        uses: excitedleigh/setup-nox@v2
      - name: Run Nox
        run: nox
